apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-app
spec:
  selector:
    matchLabels:
      app: flow-app
  replicas: 1
  template:
    metadata:
      labels:
        app: flow-app
    spec:
      containers:
        - name: flow-app
          image: cosmind7/flow-app:v3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: flow-angular-service
  labels:
    app: flow-app
spec:
  selector:
    app: flow-app
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080